spring:
  application:
    name: chinese-scramble-game

  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:chinesescramble}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      pool-name: ChineseScrambleHikariCP

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from 'update' - use Flyway for schema changes
    show-sql: false
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    open-in-view: false

  # H2 Console (Development only - DISABLED by default for security)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}  # Changed from 'true' - must explicitly enable in dev
      path: /h2-console
      settings:
        web-allow-others: false

  # Jackson JSON Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC

  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

  # Security Configuration
  security:
    jwt:
      # CRITICAL: JWT_SECRET environment variable MUST be set - no default for security
      # Generate secure secret: openssl rand -hex 64
      secret: ${JWT_SECRET}
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days in milliseconds

  # File Upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # HTTP Encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.govtech.chinesescramble: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    # SQL logging removed from base config - only in dev profile for security
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false

# Application-Specific Configuration
app:
  # Configuration file paths
  config:
    idioms-file: classpath:config/idioms.json
    sentences-file: classpath:config/sentences.json

  # Feature Flags (Default values, can be overridden in database)
  features:
    idiom-scramble: ${ENABLE_IDIOM_SCRAMBLE:true}
    sentence-crafting: ${ENABLE_SENTENCE_CRAFTING:true}
    leaderboard: ${ENABLE_LEADERBOARD:true}
    audio-pronunciation: ${ENABLE_AUDIO_PRONUNCIATION:true}
    hints: ${ENABLE_HINTS:true}
    practice-mode: ${ENABLE_PRACTICE_MODE:true}
    achievements: ${ENABLE_ACHIEVEMENTS:true}

  # Game Configuration
  game:
    # Idiom Game Settings
    idiom:
      easy:
        time-limit: 180 # 3 minutes
        base-points: 100
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 1.0
      medium:
        time-limit: 120 # 2 minutes
        base-points: 200
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 1.5
      hard:
        time-limit: 90 # 1.5 minutes
        base-points: 300
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 2.0
      expert:
        time-limit: 60 # 1 minute
        base-points: 500
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 3.0

    # Sentence Game Settings
    sentence:
      easy:
        time-limit: 180
        base-points: 100
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 1.0
      medium:
        time-limit: 120
        base-points: 200
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 1.5
      hard:
        time-limit: 90
        base-points: 300
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 2.0
      expert:
        time-limit: 60
        base-points: 500
        time-bonus-multiplier: 0.5
        difficulty-multiplier: 3.0

    # Hint System
    hints:
      level1-penalty: 10
      level2-penalty: 20
      level3-penalty: 30
      max-hints-per-question: 3

    # Leaderboard
    leaderboard:
      top-count: 10
      cache-ttl-minutes: 5

  # Security Configuration
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

    # Rate Limiting (requests per minute)
    rate-limit:
      validate-endpoint: 10
      config-endpoint: 5
      default: 100

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:chinesescramble_dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Enable H2 console in dev only
  h2:
    console:
      enabled: true

  # Development-only JWT secret (NEVER use in production)
  security:
    jwt:
      secret: ${JWT_SECRET:DEV_ONLY_SECRET_5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437_NOT_FOR_PRODUCTION}

logging:
  level:
    com.govtech.chinesescramble: DEBUG
    org.springframework.web: DEBUG
    # SQL logging enabled in dev only
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chinesescramble}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
    com.govtech.chinesescramble: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

server:
  error:
    include-stacktrace: never
    include-message: always